### ISSUE TITLE
Files not moved to fusion directory and still owned by root

### ISSUE THREAD

**Issue by rcurrie** [UCSC-Treehouse/fusion#3]
Just ran using the docker and the files all appear directly in the outputs folder vs. under fusion/ and the ownership is all still root:root.

Run command:
docker run --rm \
        -v /scratch/rcurrie/pipelines/outputs:/data/outputs \
        -v /scratch/rcurrie/pipelines/samples:/data/samples \
        -v /scratch/rcurrie/pipelines/references:/data/references \
        ucsctreehouse/fusion:0.1.0 \
                --left_fq samples/TEST_R1.fastq.gz \
                --right_fq samples/TEST_R2.fastq.gz \
                --output_dir outputs \
                --CPU `nproc` \
                --genome_lib_dir references/STARFusion-GRCh38gencode23 \
                --run_fusion_inspector

**Comment by jpfeil** [comment]
I found the bug and I'm fixing it now. Thank you!

**Comment by jpfeil** [comment]
@rcurrie, can you try this again and let me know if it works now.

**Comment by rcurrie** [comment]
Will do

**Comment by rcurrie** [comment]
Works! Closing.
