### ISSUE TITLE
Don't create empty bedpe

### ISSUE THREAD

**Issue by Jeltje** [UCSC-Treehouse/fusion#6]
Right now the program creates two `.bedpe` files, one for each of the star outputs `star-fusion-gene-list-filtered.final` and `star-fusion-non-filtered.final`. Since `.bedpe` has no header, this means empty files are created when no genes passed the filter. CGP has a problem with uploading empty files.

If no `.bedpe` file is created in _some_ runs, the CWL must be altered to allow this. Alternatively (and possibly a cleaner solution) is to create a `.tar` file as optional output.

I am not a member of this repo but I am assigning myself to fix this.

**Comment by jpfeil** [comment]
Jeltje, I'm going to refactor the code and add a bedpe header. I'll keep you updated on the changes.

**Comment by jpfeil** [comment]
This is no longer needed because we are not using BEDPE format.
